### ISSUE TITLE
bug: loses context of nested object types (dict vs OrderedDict)

### ISSUE THREAD

**Issue by SethFalco** [lekma/script.module.iapc#3]
When loading a dictionary written by this script, it reads back as a normal dictionary regardless of what type of dictionary subclass we're serializing from.

The impact is that in `plugin.video.invidious` for example, on first use, an `OrderedDict` is created in memory, but once persisted and loaded back in, it's a regular `dict` instead. 

This means we're unable to rely on functions like [`OrderedDict#move_to_end`](https://docs.python.org/3/library/collections.html#collections.OrderedDict.move_to_end) which are specific to `OrderedDict`.

Even if we changed the class to `class SearchHistory(Persistent, OrderedDict):`, the nested dictionaries will still be read as a `dict`.

Reference: https://github.com/lekma/plugin.video.invidious/blob/master/lib/invidious/persistence.py#L62

I'm not familiar with this project yet, but happy to discuss potential solutions. I don't have anything in mind for handling nested objects yet, though.

For now, my thoughts are that maybe handling subclasses should be considered out of scope for this library, and instead `plugin.video.invidious` should process data received, and convert the nested dictionaries to an `OrderedDict` before `SearchHistory` handles it? :thinking:

Just wanted to ask about it here first, though!

---

PS: Working on a PR for `plugin.video.invidious` so that when someone accesses a previous search, or types an old search again, it gets moved to the top of the search history.

I would prefer to use [`OrderedDict#move_to_end`](https://docs.python.org/3/library/collections.html#collections.OrderedDict.move_to_end), but due to this bug, I'll instead do `#remove` then `#record` for now.

**Comment by lekma** [comment]
Yep, you're right. that is an overlooked unfortunate side effect of moving from `pickle` to `json`.
But solving it in iapc would involve re-implementing the whole persistence system (which I'm not opposed to) and find a way to mark all objects with type annotations (I'll not dive in that rabbit hole ever again (also json performance)).

Now you can work around it in invidious by doing something like that:

```diff
diff --git a/lib/invidious/persistence.py b/lib/invidious/persistence.py
index a7bc50d..e2ec97d 100644
--- a/lib/invidious/persistence.py
+++ b/lib/invidious/persistence.py
@@ -56,7 +56,10 @@ search_cache = SearchCache()
 # ------------------------------------------------------------------------------
 # SearchHistory
 
-class SearchHistory(Persistent, dict):
+class SearchHistory(Persistent, OrderedDict):
+
+    def __setitem__(self, key, value):
+        super(SearchHistory, self).__setitem__(key, OrderedDict(value))
 
     def __missing__(self, key):
         self[key] = OrderedDict()
@@ -65,6 +68,7 @@ class SearchHistory(Persistent, dict):
     @save
     def record(self, type, query, sort_by):
         self[type][query] = {"type": type, "query": query, "sort_by": sort_by}
+        self[type].move_to_end(query)
 
     @save
     def remove(self, type, query):
```

the change from `dict` to `OrderedDict` in the bases is only needed to change the mro...

**Comment by SethFalco** [comment]
Hey hey!

Gave this a try, and it works very well. ^-^
I've updated my PR.

I'll leave it up to you if you want to keep this issue open or closed.
